[package]
name = "sigma_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.152"
serde_yaml = { version = "0.9.17", features = ["derive"] } 
